const CHANGE_NAME = 'CHANGE_NAME';
const CHANGE_NATIONALITY = 'CHANGE_NATIONALITY';
const CHANGE_PHONE_NUMBER = 'CHANGE_PHONE_NUMBER';
const CLEAR_ALL = 'CLEAR_ALL';

export { CHANGE_NAME, CHANGE_NATIONALITY, CHANGE_PHONE_NUMBER, CLEAR_ALL };

