import { CHANGE_NAME, CHANGE_NATIONALITY, CHANGE_PHONE_NUMBER, CLEAR_ALL } from './actionTypes';
import { OK, ERROR, ERROR_REQUIRED, ERROR_INVALID_PHONE_NUMBER, isOK, isERROR } from './validationStatus';

export {
  CHANGE_NAME,
  CHANGE_NATIONALITY,
  CHANGE_PHONE_NUMBER,
  CLEAR_ALL,
  OK,
  ERROR,
  ERROR_REQUIRED,
  ERROR_INVALID_PHONE_NUMBER,
  isOK,
  isERROR,
};
